### ISSUE TITLE
Issues with Builder Preview

### ISSUE THREAD

**Issue by stvtk** [pboivin/filament-peek#86]
Hello there,

I hope you're doing well.

I noticed that there's an issue with Builder Preview. If you click on the builder preview multiple times, instead of opening the builder preview it will open the preview Modal.

You can reproduce this in the demo itself, I used https://github.com/pboivin/filament-peek-demo and was able to replicate it.

Steps to replicate:

1 - Setup the demo locally by following the documentation in https://github.com/pboivin/filament-peek-demo
2 - Go to any post entry (for example, http://127.0.0.1:8000/admin/posts/1/edit)
3 - Click on **Preview Content Blocks**
- The Builder Preview will open which is the expected behavior
4 - Now Click on Discard, and click on the same button  **Preview Content Blocks**
- The Preview Modal will show instead of the Builder Preview. Which is not the expected Behavior. 

Is this a known issue or just me facing it?

Kindest Regards,

Moustafa

**Comment by pboivin** [comment]
Hi @stvtk, thanks for reporting the issue, I can replicate it following your instructions.

I think the issue is with the new `InlinePreviewAction` component. I'll take some time to investigate but as a temporary fix, you can switch back to the old `PreviewLink` component instead:

```php
    PreviewLink::make()
        ->label('Preview Content Blocks')
        ->builderPreview('content_blocks')
        ->columnSpanFull()
        ->alignRight(),
```

[Reference here](https://github.com/pboivin/filament-peek-demo/blob/44ff7dd06fcb9cd38d72e876a21367998ca3a454/app/Filament/Resources/PostResource.php#L58-L62)

**Comment by stvtk** [comment]
Hello @pboivin, Thank you for the temporary fix!

appreciated!
